# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentdm", "0002_sentdmcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentdmprofile",
            name="whatsapp_connection_source",
            field=models.CharField(
                choices=[
                    ("none", "Not Connected"),
                    ("inherited", "Inherited Organization WhatsApp"),
                    ("direct", "Agent Direct WhatsApp"),
                ],
                db_index=True,
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sentdmprofile",
            name="whatsapp_connection_status",
            field=models.CharField(
                choices=[
                    ("not_connected", "Not Connected"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="not_connected",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sentdmprofile",
            name="whatsapp_connection_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sentdmprofile",
            name="whatsapp_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sentdmprofile",
            name="whatsapp_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]