# Generated by Django 6.0.6 on 2026-09-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_normalize_sentdm_expected_daily_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sentdm_whatsapp_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='sentdm_whatsapp_phone_number_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='sentdm_whatsapp_waba_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
