# Generated by Django 6.0.6 on 2026-09-15 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome'), ('new_user', 'New User'), ('subscription_created', 'Subscription Created'), ('subscription_active', 'Subscription Active'), ('sentdm_profile_requested', 'Sent.dm Profile Requested'), ('sentdm_profile_completed', 'Sent.dm Profile Completed'), ('sentdm_campaign_requested', 'Sent.dm Campaign Requested'), ('whatsapp_connection_requested', 'WhatsApp Connection Requested'), ('new_lead', 'New Lead'), ('message_received', 'Message Received'), ('system_alert', 'System Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
